from Modules.BasePop import *
from Modules.Matrix import *
from Modules.TournamentSelection import *
from Modules.Pairindividuals import *
from Modules.CrossoverPMX import *
from Modules.CrossoverOX import *
from Modules.CrossoverCX import *
from Modules.Rate import *
from Modules.Mutation import *
from Modules.RouletteSelection import *
from Modules.MutationBomb import *